name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # macOS (Intel)
            args: '--target x86_64-apple-darwin'

          - platform: 'macos-latest' # macOS (Apple Silicon)
            args: '--target aarch64-apple-darwin'

          - platform: 'ubuntu-22.04' # Linux
            args: ''

          - platform: 'windows-latest' # Windows
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'CC Switch ${{ github.ref_name }}'
          releaseBody: |
            ## 🎉 CC Switch ${{ github.ref_name }}

            ### 下载说明
            请从下方的 Assets 中下载对应平台的安装包

            ### 更新内容
            请查看提交记录了解详细更新内容。
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
